title: APER Forum
url: "https://aperforum.org" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/Webp.net-resizeimage.png

// HLB brand colors
colors:
  primary-color: '#2A4F8F'
  secondary-color: '#396AD4'
  media-colors:
    - title: media-color-one
      color: '#2A4F8F'
    - title: media-color-two
      color: '#2A4F8F'
    - title: media-color-three
      color: '#2A4F8F'
    - title: media-color-four
      color: '#2A4F8F'
    - title: media-color-five
      color: '#2A4F8F'

collections:
  about:
    output: true
  APER-extraordinary-meeting:
    output: true
  archives:
    output: true

google_analytics: UA-173919789-1
resources_name: newsroom

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: Singapore will be hosting the Asia Pacific Energy Regulatory Forum in 2020/2021.

